# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alnisa Surgical Instruments
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/alnisa" # the subpath of your site, e.g. /blog
url: "https://dilan101010.github.io" # the base hostname & protocol for your site
logo: "/images/logo.JPG"
pin_address: Lorem lkojdsf jdshf sdhfj
mobile:  "099XXXXXXXX"
mobile1: "087787XXXXX"
fax: "XXXXXXXXXX"

facebook: "https://www.facebook.com"
twitter: "https://www.twitter.com"
google_plus: "https://www.google.com"

copyright: © 2019 Alnisa Surgical Instruments - All rights reserved.

catalog_title: Alnisa Surgical Instruments CATALOGOS
catalog_desc: Download our PDF catalogue. Along with the ability for customers to view and purchase PenmanDirect's products on our online store, our redesigned catalogue ...
catalog_image: "/images/pdfbook.jpg"

# Build settings
markdown: kramdown
include: ["_pages"]
exclude: ["README.md"]

collections:
  product:
    output: true
    permalink: /product/:path/
    layout: product

defaults:
  - scope:
      type: product
    values:
      layout: product

plugins:
  - github-pages
  # - piwigo_gallery

piwigo_gallery:
    baseurl: http://photos.gallery.com/piwigo/
